### ISSUE TITLE
not working in windows

### ISSUE THREAD

**Issue by aamiyuva** [barungh/LCM-Python-Flask#2]
the code is not working in windows powershell

**Comment by barungh** [comment]
Did you check Flask is installed properly ?

What issues are you getting ?

Can you post the details ?

This might help
![image](https://user-images.githubusercontent.com/12285528/188791545-07f73fe2-fafd-43cd-80eb-8630ada15b41.png)

[Doc](https://flask.palletsprojects.com/en/1.1.x/tutorial/factory/)
